# Generated by Django 6.1.1 on 2026-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehical_db',
            fields=[
                ('Vehical_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehical_reg_date', models.DateField()),
                ('Vehical_type', models.CharField(max_length=20)),
                ('Model_number', models.CharField(max_length=10)),
                ('vehical_owner', models.CharField(max_length=30)),
                ('Owner_lis_num', models.CharField(max_length=20)),
                ('Owner_Contact_Num', models.IntegerField()),
            ],
        ),
    ]
